music_ref_table = {'mx/adine3.ogg': {'album': 'Soundtrack from a Box 10',
                   'artist': 'Crinkles',
                   'title': 'Sunset'},
 'mx/anna3.ogg': {'album': 'Soundtrack from a Box 15',
                  'artist': 'Crinkles',
                  'title': 'Hay'},
 'mx/anna3x.ogg': {'album': 'Soundtrack From A Box 9',
                   'artist': 'Crinkles',
                   'title': 'Memories'},
 'mx/anna4.ogg': {'album': 'Soundtrack from a Box 4',
                  'artist': 'Crinkles',
                  'title': 'Fireflies'},
 'mx/aquavitae.ogg': {'artist': 'Alcaknight',
                      'title': 'ALOriginal Ambient Track - Aqua Vitae.ogg'},
 'mx/archaic.ogg': {'album': 'Soundtrack from a Box 6',
                    'artist': 'Crinkles\x01\x05vorbis+BCV',
                    'title': 'Archaic Times'},
 'mx/archives.ogg': {'album': 'Soundtrack from a Box 10',
                     'artist': 'Crinkles',
                     'title': 'Archives'},
 'mx/ashes.ogg': {'album': 'Soundtrack from a Box 10',
                  'artist': 'Crinkles',
                  'title': 'Ashes'},
 'mx/barren.ogg': {'album': 'Soundtrack from a Box 1',
                   'artist': 'Crinkles',
                   'title': 'Barren World'},
 'mx/basicguitar.ogg': {'album': '70 Days',
                        'artist': 'Mark Sparling',
                        'title': 'day 32'},
 'mx/basicguitar2.ogg': {'artist': 'Mark Sparling',
                         'title': 'mx/basicguitar2.ogg'},
 'mx/bells.ogg': {'artist': 'Mark Sparling', 'title': 'mx/bells.ogg'},
 'mx/bubbles.ogg': {'album': 'Soundtrack from a Box 5',
                    'artist': 'Crinkles\x01\x05vorbis+BCV',
                    'title': 'Bubbles'},
 'mx/campfire.ogg': {'album': 'Soundtrack From A Box 7',
                     'artist': 'Crinkles\x01\x05vorbis+BCV',
                     'title': 'Campfire'},
 'mx/chip.ogg': {'album': 'Soundtrack from a Box 15',
                 'artist': 'Crinkles',
                 'title': 'Chip'},
 'mx/choices.ogg': {'album': 'Soundtrack From A Box 9',
                    'artist': 'Crinkles\x01\x05vorbis+BCV',
                    'title': 'Choices'},
 'mx/chronos.ogg': {'album': 'Soundtrack from a Box 6',
                    'artist': 'Crinkles',
                    'title': 'Chronos'},
 'mx/clocks.ogg': {'album': 'Soundtrack from a Box 6',
                   'artist': 'Crinkles',
                   'title': 'Clocks'},
 'mx/clouds.ogg': {'album': 'Soundtrack from a Box 4',
                   'artist': 'Crinkles\x01\x05vorbis+BCV',
                   'title': 'Up in the Clouds'},
 'mx/confrontation.ogg': {'artist': 'Crinkles',
                          'title': 'mx/confrontation.ogg'},
 'mx/creamclouds.ogg': {'album': 'Soundtrack from a Box 6',
                        'artist': 'Crinkles',
                        'title': 'Cream Clouds'},
 'mx/cruising.ogg': {'album': 'Soundtrack From A Box 8',
                     'artist': 'Crinkles',
                     'title': 'Cruising'},
 'mx/cute.ogg': {'artist': 'Mark Sparling', 'title': 'mx/cute.ogg'},
 'mx/damion.ogg': {'album': 'Soundtrack from a Box 15',
                   'artist': 'Crinkles',
                   'title': 'Bricks'},
 'mx/darkrock.ogg': {'artist': 'Mark Sparling',
                     'title': 'darkrockEVILENDING.ogg'},
 'mx/dash.ogg': {'artist': 'Alcaknight', 'title': 'ALCAKNIGHTDash (Loop).ogg'},
 'mx/day10.ogg': {'artist': 'Mark Sparling', 'title': 'mx/day10.ogg'},
 'mx/detective.ogg': {'artist': 'Mark Sparling', 'title': 'mx/detective.ogg'},
 'mx/disturbance.ogg': {'album': 'Soundtrack from a Box 11',
                        'artist': 'Crinkles',
                        'title': 'Disturbance'},
 'mx/dramatic.ogg': {'album': '70 Days',
                     'artist': 'Mark Sparling',
                     'title': 'mx/dramatic.ogg'},
 'mx/elegant.ogg': {'album': 'Soundtrack from a Box 1',
                    'artist': 'Crinkles',
                    'title': 'Mining Town'},
 'mx/eveningmelody.ogg': {'artist': 'Alcaknight',
                          'title': 'ALEvening Melody.ogg'},
 'mx/feelings.ogg': {'album': 'Soundtrack from a Box 10',
                     'artist': 'Crinkles',
                     'title': 'Feelings'},
 'mx/fervor.ogg': {'album': 'Soundtrack from a Box 15',
                   'artist': 'Crinkles',
                   'title': 'Fervor'},
 'mx/fireplace.ogg': {'album': 'Soundtrack From A Box 8',
                      'artist': 'Crinkles\x01\x05vorbis+BCV',
                      'title': 'Fireplace'},
 'mx/flashback.ogg': {'album': 'Soundtrack from a Box 2',
                      'artist': 'Crinkles',
                      'title': 'A Gift'},
 'mx/fleet.ogg': {'album': 'Soundtrack from a Box 15',
                  'artist': 'Crinkles',
                  'title': 'Fleet'},
 'mx/flux.ogg': {'artist': 'Crinkles',
                 'title': 'Crinkles - Soundtrack from a Box 16 - 11 Flux.ogg'},
 'mx/forge.ogg': {'album': 'Soundtrack from a Box 12',
                  'artist': 'Crinkles',
                  'title': 'Forge'},
 'mx/fountain.ogg': {'album': 'Soundtrack from a Box 15',
                     'artist': 'Crinkles',
                     'title': 'Fountain'},
 'mx/fragilemind.ogg': {'album': 'Soundtrack from a Box 3',
                        'artist': 'Crinkles',
                        'title': 'Fragile Mind'},
 'mx/fragments.ogg': {'album': 'Soundtrack from a Box 12',
                      'artist': 'Crinkles',
                      'title': 'Fragments'},
 'mx/fun.ogg': {'artist': 'Mark Sparling', 'title': 'mx/fun.ogg'},
 'mx/funness.ogg': {'artist': 'Mark Sparling', 'title': 'mx/funness.ogg'},
 'mx/general.ogg': {'album': '70 Days',
                    'artist': 'Mark Sparling',
                    'title': 'day 52'},
 'mx/gravity.ogg': {'album': 'Soundtrack from a Box 12',
                    'artist': 'Crinkles',
                    'title': 'Gravity'},
 'mx/heavy.ogg': {'album': '70 Days',
                  'artist': 'Mark Sparling',
                  'title': 'day 37'},
 'mx/hopefulAMELY.ogg': {'artist': 'Mark Sparling',
                         'title': 'mx/hopefulAMELY.ogg'},
 'mx/hydrangea.ogg': {'album': 'Soundtrack from a Box 15',
                      'artist': 'Crinkles',
                      'title': 'Hydrangea'},
 'mx/intrigue.ogg': {'album': '70 Days',
                     'artist': 'Mark Sparling',
                     'title': 'day 23'},
 'mx/introtheme.ogg': {'album': '70 Days',
                       'artist': 'Mark Sparling',
                       'title': 'day 9'},
 'mx/investigation.ogg': {'album': 'Soundtrack from a Box 3',
                          'artist': 'Crinkles\x01\x05vorbis+BCV',
                          'title': 'Determination'},
 'mx/jazzy.ogg': {'artist': 'Mark Sparling', 'title': 'mx/jazzy.ogg'},
 'mx/jazzy2.ogg': {'album': '70 Days',
                   'artist': 'Mark Sparling',
                   'title': 'day 19'},
 'mx/judgement.ogg': {'album': 'Soundtrack from a Box 2',
                      'artist': 'Crinkles',
                      'title': 'Judgement'},
 'mx/library.ogg': {'artist': 'Crinkles',
                    'title': 'Crinkles - Soundtrack from a Box 16 - 08 Arcane '
                             'Library.ogg'},
 'mx/markday10.ogg': {'artist': 'Mark Sparling', 'title': 'markday 10.ogg'},
 'mx/martyr.ogg': {'album': 'Soundtrack from a Box 15',
                   'artist': 'Crinkles',
                   'title': 'Martyr'},
 'mx/menu.ogg': {'artist': 'Mark Sparling', 'title': 'mx/menu.ogg'},
 'mx/mindstream.ogg': {'album': 'Soundtrack From A Box 9',
                       'artist': 'Crinkles',
                       'title': 'Mindstream'},
 'mx/morningrise.ogg': {'album': 'Soundtrack from a Box 3',
                        'artist': 'Crinkles',
                        'title': 'Morning Rise'},
 'mx/movingon.ogg': {'album': 'Soundtrack from a Box 13',
                     'artist': 'Crinkles',
                     'title': 'Moving on'},
 'mx/mystery2.ogg': {'artist': 'Mark Sparling', 'title': 'mx/mystery2.ogg'},
 'mx/mysteryambience.ogg': {'artist': 'Mark Sparling',
                            'title': 'mx/mysteryambience.ogg'},
 'mx/nostalgia.ogg': {'artist': 'Alcaknight', 'title': 'mx/nostalgia.ogg'},
 'mx/path.ogg': {'album': 'Soundtrack from a Box 4',
                 'artist': 'Crinkles',
                 'title': 'Ancient Path'},
 'mx/politics.ogg': {'album': 'Soundtrack from a Box 10',
                     'artist': 'Crinkles',
                     'title': 'Countess'},
 'mx/prayer.ogg': {'album': 'Soundtrack from a Box 10',
                   'artist': 'Crinkles',
                   'title': 'Prayer'},
 'mx/prophecy.ogg': {'album': 'Soundtrack from a Box 13',
                     'artist': 'Crinkles',
                     'title': 'Prophecy'},
 'mx/rezatheme.ogg': {'artist': 'Mark Sparling', 'title': 'mx/rezatheme.ogg'},
 'mx/sad.ogg': {'artist': 'Mark Sparling', 'title': 'mx/sad.ogg'},
 'mx/sail.ogg': {'album': 'Soundtrack From A Box 7',
                 'artist': 'Crinkles\x01\x05vorbis+BCV',
                 'title': 'Setting Sail'},
 'mx/schizophrenia.ogg': {'artist': 'Crinkles',
                          'title': 'SchizophreniaANNApayoff.ogg'},
 'mx/serene.ogg': {'album': '70 Days',
                   'artist': 'Mark Sparling',
                   'title': 'day 51'},
 'mx/shoal.ogg': {'album': 'Soundtrack from a Box 15',
                  'artist': 'Crinkles',
                  'title': 'Shoal'},
 'mx/sleepingcity.ogg': {'artist': 'Alcaknight',
                         'title': 'ALThe Sleeping City.ogg'},
 'mx/slow.ogg': {'artist': 'Mark Sparling', 'title': 'slowFLASHBACK.ogg'},
 'mx/slowpiano.ogg': {'album': '70 Days',
                      'artist': 'Mark Sparling',
                      'title': 'day 22'},
 'mx/snowflake.ogg': {'album': 'Soundtrack from a Box 12',
                      'artist': 'Crinkles',
                      'title': 'Snowflake'},
 'mx/soul.ogg': {'album': 'Soundtrack from a Box 2',
                 'artist': 'Crinkles',
                 'title': 'Wandering Soul'},
 'mx/spring.ogg': {'album': 'Soundtrack from a Box 13',
                   'artist': 'Crinkles',
                   'title': 'Spring'},
 'mx/sprite.ogg': {'album': 'Soundtrack from a Box 12',
                   'artist': 'Crinkles',
                   'title': 'Sprite'},
 'mx/starlight.ogg': {'album': 'Soundtrack from a Box 15',
                      'artist': 'Crinkles',
                      'title': 'Starlight'},
 'mx/sweetmemories.ogg': {'artist': 'Alcaknight',
                          'title': 'ALSweet Memories.ogg'},
 'mx/termination.ogg': {'artist': 'Mark Sparling', 'title': 'terminator.ogg'},
 'mx/threat.ogg': {'album': '70 Days',
                   'artist': 'Mark Sparling',
                   'title': 'day 16'},
 'mx/tranquility.ogg': {'album': 'Soundtrack From A Box 7',
                        'artist': 'Crinkles',
                        'title': 'Tranquility'},
 'mx/warming.ogg': {'album': 'Soundtrack From A Box 8',
                    'artist': 'Crinkles',
                    'title': 'Warming'},
 'mx/zhong.ogg': {'album': 'Soundtrack From A Box 8',
                  'artist': 'Crinkles',
                  'title': 'On the rocks'},
 'mx/zhongrock.ogg': {'artist': 'Mark Sparling', 'title': 'mx/zhongrock.ogg'}}
